runtime! debian.vim

if has("syntax")
  syntax on
endif

set showcmd		
set showmatch		
set ignorecase		
set smartcase		
set incsearch		
set hlsearch
set autowrite		
set hidden		
set mouse=a		

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

:map <C-a> ggVG
:map <C-e> ggVGg?
